# Generated by Django 5.2.5 on 2025-09-06 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0002_booking_created_at_booking_guest_and_more'),
        ('tourpackets', '0001_initial'),
        ('users', '0002_user_is_tourguide_tourguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatIsIncluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='whatisincluded/')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cityandcountry'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_in_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='hosted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tourguide'),
        ),
        migrations.AddField(
            model_name='tour',
            name='hosted_languages',
            field=models.ManyToManyField(blank=True, to='users.language'),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accomodations.locations'),
        ),
        migrations.AddField(
            model_name='tour',
            name='what_is_included',
            field=models.ManyToManyField(blank=True, to='tourpackets.whatisincluded'),
        ),
    ]
